sudo: false
language: rust

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin`
  fi