[package]
name = "casspir"
description = "Minesweeper puzzle generator and solver."
version = "0.2.0"
edition = "2018"
readme = "README.md"
authors = ["dylan.mcgannon@gmail.com"]
license = "LGPL-3.0-or-later"

[dependencies]
rand = "0.8"